/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./src/components/Alert/alert.vue')['default']
    'Alert.component': typeof import('./src/components/alert/alert.component.vue')['default']
    ArticleItem: typeof import('./src/components/article-item/ArticleItem.vue')['default']
    'ArticleItem.component': typeof import('./src/components/article-item/article-item.component.vue')['default']
    Avatar: typeof import('./src/components/Avatar/Avatar.vue')['default']
    'Avatar.component': typeof import('./src/components/menu/avatar/avatar.component.vue')['default']
    'ChangePasswordForm.component': typeof import('./src/components/form-change-password/change-password-form.component.vue')['default']
    DateDialog: typeof import('./src/components/FormCriterias/DateDialog/DateDialog.vue')['default']
    'DateDialog.component': typeof import('./src/components/form-criterias/date-dialog/date-dialog.component.vue')['default']
    DialogViewArticle: typeof import('./src/components/dialog-view-article/DialogViewArticle.vue')['default']
    'DialogViewArticle.component': typeof import('./src/components/dialog-view-article/dialog-view-article.component.vue')['default']
    FormArticle: typeof import('./src/components/form-article/FormArticle.vue')['default']
    'FormArticle.component': typeof import('./src/components/form-article/form-article.component.vue')['default']
    'FormChangePassword.component': typeof import('./src/components/form-change-password/form-change-password.component.vue')['default']
    FormConnexion: typeof import('./src/components/form-connexion/FormConnexion.vue')['default']
    'FormConnexion.component': typeof import('./src/components/form-connexion/form-connexion.component.vue')['default']
    FormCriterias: typeof import('./src/components/FormCriterias/FormCriterias.vue')['default']
    'FormCriterias.component': typeof import('./src/components/form-criterias/form-criterias.component.vue')['default']
    FormRegistration: typeof import('./src/components/FormRegistration/FormRegistration.vue')['default']
    'FormRegistration.component': typeof import('./src/components/form-registration/form-registration.component.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ListArticles: typeof import('./src/components/ListArticles/ListArticles.vue')['default']
    'ListArticles.component': typeof import('./src/components/list-articles/list-articles.component.vue')['default']
    Menu: typeof import('./src/components/Menu/Menu.vue')['default']
    'Menu.component': typeof import('./src/components/menu/menu.component.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
